# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

$script1 = <<END
    mkdir -p ~root/.ssh
    cp ~vagrant/.ssh/auth* ~root/.ssh
    yum install -y epel-release
    yes | rpm -ivh http://ftp.tu-chemnitz.de/pub/linux/dag/redhat/el7/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm
    yum install -y vim redhat-lsb-core wget yum-utils htop mc screen sudo iotop net-tools elinks traceroute bind-utils deltarpm lsof vim vim-enhanced nmap
    echo "alias vi='vim'" >> /root/.bashrc
    echo "colorscheme desert" >> /etc/vimrc
END

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.ssh.forward_x11 = true

  config.vm.define "ipaclient" do |t|
  end

  config.vm.define "ipaclient" do |machine|

    machine.vm.hostname = "ipaclient.otus.loc"
    machine.vm.network "private_network", ip: "172.17.177.11", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ipa_net"
    machine.vm.provision "shell", inline: $script1
    machine.vm.provision "shell", inline: <<-SHELL
    cat /vagrant/keys/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    echo "172.17.177.11 ipaclient.otus.loc ipaclient" > /etc/hosts
    echo "172.17.177.22 ipaserver.otus.loc ipaserver" >> /etc/hosts
    SHELL

     config.vm.provider "virtualbox" do |vb|
       vb.name = "ipaclient"
       vb.memory = "1024"
       vb.cpus = "1"
     end
  end

  config.vm.define "ipaserver" do |t|
  end

  config.vm.define "ipaserver" do |machine|

    machine.vm.hostname = "ipaserver.otus.loc"
    machine.vm.network "private_network", ip: "172.17.177.22", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ipa_net"
    machine.vm.network "public_network", adapter: 3, bridge: "wlp2s0"
    machine.vm.provision "shell", inline: $script1
    machine.vm.provision "shell", inline: <<-SHELL
    cp /vagrant/keys/id_rsa* /home/vagrant/.ssh/
    chmod 700 /home/vagrant/.ssh/ && chmod 600 /home/vagrant/.ssh/*
    chown vagrant:vagrant /home/vagrant/.ssh/id_rsa*
    echo "172.17.177.22 ipaserver.otus.loc ipaserver" > /etc/hosts
    echo "172.17.177.11 ipaclient.otus.loc ipaclient" >> /etc/hosts
    yum install -y python python-setuptools
    yum install -y xorg-x11-server-Xorg xorg-x11-server-utils x11vnc firefox
    easy_install pip
    pip install ansible
    mkdir -p /etc/ansible/
    echo "[defaults]
host_key_checking = False" > /etc/ansible/ansible.cfg

    mkdir /home/vagrant/ansible
    cp -r /vagrant/ansible/* /home/vagrant/ansible/
    chown vagrant:vagrant -R /home/vagrant/ansible
    
    sudo -u vagrant ansible all -i /home/vagrant/ansible/hosts -m ping
    ansible-playbook -v /home/vagrant/ansible/playbook_ipa-server.yml -i /home/vagrant/ansible/hosts --list-tasks
    ansible-playbook -v /home/vagrant/ansible/playbook_ipa-server.yml -i /home/vagrant/ansible/hosts
    sleep 10
    sudo -u vagrant ansible-playbook -v /home/vagrant/ansible/playbook_ipa-client.yml -i /home/vagrant/ansible/hosts --list-tasks
    sudo -u vagrant ansible-playbook -v /home/vagrant/ansible/playbook_ipa-client.yml -i /home/vagrant/ansible/hosts
    echo "---------------------------------------------------------------------------------"
    echo "-----------------------------------RESULT----------------------------------------"
    echo "теперь можно подключиться такой командой к ipaserver (стоит проверить ваш порт ssh на этой ВМ):"
    echo "ssh -i .vagrant/machines/ipaserver/virtualbox/private_key -p 2200 -X vagrant@127.0.0.1"
    echo "запустить firefox:"
    echo "xhost 10.0.2.15 && firefox"
    echo "в запустившемся firefox открыть адрес http://ipaserver.otus.loc, ввести логин admin, пароль otusotus"
    echo "и на вкладке с узлами будет виден только что подключенный ipaclient.otus.loc"
    echo "--------------------------------END RESULTS--------------------------------------"
    echo "---------------------------------------------------------------------------------"
    SHELL

     config.vm.provider "virtualbox" do |vb|
       vb.name = "ipaserver"
       vb.memory = "4096"
       vb.cpus = "2"
     end
  end

end
