#!/usr/bin/env bash

LOG=/tmp/pam_script_auth.log
DAY_OF_THE_WEEK=$(date +%u)
LOGIN_TIME=$(date --iso-8601=seconds)
TEST_USER=$(grep $PAM_USER /etc/group | grep ^admin | wc -l)
TODAY=$(date "+%Y%m%d")

CALENDAR=$(curl -s https://isdayoff.ru/$TODAY)
#0 - рабочий день
#1 - выходной или праздничный день

FUNC_LOG_0 ()
{
echo "-------------------------------" >> $LOG
echo "PAM_USER=$PAM_USER" >> $LOG
echo "DAY_OF_THE_WEEK=$DAY_OF_THE_WEEK" >> $LOG
echo "LOGIN_TIME=$LOGIN_TIME" >> $LOG
echo "TODAY=$TODAY" >> $LOG
echo "CALENDAR=$CALENDAR" >> $LOG
echo "exit 0" >> $LOG
}

FUNC_LOG_1 ()
{
echo "-------------------------------" >> $LOG
echo "ALERT!!!" >> $LOG
echo -e "PAM_USER=$PAM_USER" >> $LOG
echo "DAY_OF_THE_WEEK=$DAY_OF_THE_WEEK" >> $LOG
echo "LOGIN_TIME=$LOGIN_TIME" >> $LOG
echo "TODAY=$TODAY" >> $LOG
echo "CALENDAR=$CALENDAR" >> $LOG
echo "exit 1" >> $LOG
}


if [ "$CALENDAR" -eq "1" ]

#f [ "$DAY_OF_THE_WEEK" -eq "6" -o "$DAY_OF_THE_WEEK" -eq "7" ]
then


    if [ "$TEST_USER" -eq "1" ]
        then
            FUNC_LOG_0
            exit 0
        else
            FUNC_LOG_1
            exit 1
    fi

else
    FUNC_LOG_0
    exit 0
fi
